#!/bin/bash

PROJ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd | sed 's/\(.*\/dev-shop\).*/\1/')"
cd "${PROJ_DIR}" || exit

NAME="dev-shop-yarn"
IMAGE="${NAME}:latest"


### MAIN

docker build -t "${IMAGE}" -f "./Dockerfile.${NAME}" .
