#!/bin/bash

PROJ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd | sed 's/\(.*\/dev-shop\).*/\1/')"
cd "${PROJ_DIR}" || exit

### MAIN

if ! docker ps | grep -q -e 'dev-shop$'; then
  #https://github.com/k3d-io/k3d/issues/855
  docker run  -d --privileged  --name dev-shop dev-shop:latest
fi

docker exec -it dev-shop bash
