FROM ubuntu:20.04
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl
RUN apt-get install -y git
RUN git version

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

# https://github.com/nvm-sh/nvm/issues/1994
SHELL ["/bin/bash", "--login", "-c"]
RUN echo "export NVM_DIR=${HOME}/.nvm" >> "${HOME}/.profile"
RUN echo ". ${HOME}/.nvm/nvm.sh" >> "${HOME}/.profile"
RUN nvm install 14
RUN echo "nvm use 14" >> "${HOME}/.profile"

RUN npm install --global yarn

RUN apt-get install -y python3.8
RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN apt-get install -y make
RUN apt-get install -y gcc build-essential
